name: workflows
on:
  workflow_call:
    inputs:
      distribution:
        type: string
        required: false
      java-version:
        type: string
        required: false
      server-id:
        type: string
        required: false
      server-username:
        type: string
        required: false
      server-password:
        type: string
        required: false
      path: 
        type: string
        required: false
      key:
        type: string
        required: false
      upload-path:
        type: string
        required: false
      cmd:
        type: string
        required: false
      build:
        type: string
        required: false
      working-directory:
        type: string
        required: false
      artifact:
        type: string
        required: false
      zip:
        type: string
        required: false
    secrets:
      access-key:
        description: 'oidc role'
        required: true
      secret-key:
        description: 'key'
        required: true  
jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Determine OS and Set Hash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
             hash_value=$(find . -name 'pom.xml' -type f -exec sha256sum {} + | sort | sha256sum | cut -d ' ' -f 1)
             else
             echo "Unsupported operating system"
             exit 1
          fi
          echo "HASH_VALUE=${hash_value}" >> $GITHUB_ENV
          echo "RUNNER_OS=${{ runner.os }}" >> $GITHUB_ENV
        env:
          #RUNNER_OS: ${{ runner.os }}
          JAVA_VERSION: $JAVA_VERSION
      - name: Set Java Version
        run: |
          if [ "$JAVA_VERSION" = "11" ]; then
            echo "JAVA_VERSION=11" >> $GITHUB_ENV
          else
            echo "JAVA_VERSION=17" >> $GITHUB_ENV
          fi
      - name: checkout
        uses: actions/cache@v2
        with:
          path: "${{inputs.path}}"
          key: "${{inputs.key}}"
      - name: java
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: "${{inputs.java-version}}"
          server-id: github
          server-username: GITHUB_USER
          server-password: GITHUB_USER_TOKEN
      - name: Checkout Java Project Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: ./
      - name: set artifact id
        run: ${{inputs.cmd}}
        #working-directory: ${{inputs.working-directory}}
      - name: build project
        run: '${{ inputs.build}}'
      - name: zip artifacts
        run: |
          ${{inputs.atrifact}}
          ${{inputs.zip}}
      - name: upload artifact
        uses: actions/upload-artifact@v3.1.3
        with: 
          name: fr.zip
          path: "${{inputs.upload-path}}"
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: '${{ secrets.access-key}}'
          aws-secret-access-key: '${{secrets.secret-key}}'
          aws-region: us-east-1
          role-duration-seconds: 3600
      #- name: login amazon ecr
